### ISSUE TITLE
List of solved theorems?

### ISSUE THREAD

**Issue by darabos** [wiio12/LEGO-Prover#1]
Hi,
Thanks for sharing this project! Fantastic results. 🥇 I wanted to check the full list of MiniF2F theorems that LEGO solved, as a way to understand the difficulty of different theorems. I looked in the files in `data/full_data`. But they are just the placeholder proofs from MiniF2F, right? Not the LEGO-generated ones?
Thanks!

**Comment by wiio12** [comment]
Hi @darabos, thank you for your attention to our project! We haven't released the full list of LEGO-generated proof since it requires further processing and some company routine before release. I am quite occupied currently but we guarantee to release all the LEGO-generated proof and the skill library in the near future!

**Comment by wiio12** [comment]
Apologies for the extended wait; the results are now available. I am proceeding to close the issues.

**Comment by darabos** [comment]
Thank you! There's lots of interesting details in the results file. It's awesome!
